In [29]:
!pip install numpy

import numpy as np

# Define Tensor A with shape (3, 4, 5)
A = np.arange(  3, 4, 5)

# Define Tensor B with shape (5, 4, 6)
B = np.random.rand(5, 4, 6)

# a = np.array([
#       [1.0, 2.0, 3.0, 7.0], 
#       [4.0, 5.0, 6.0, 8.0] 
#    ]) #(2,4)

a = np.array([
     [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], 
      [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]] 
    ]) # (2,2,3)

b =  np.array([
                  [[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]],
                  [[9.0, 10.0], [11.0, 12.0], [13.0, 14.0], [15.0, 16.0]],
                  [[17.0, 18.0], [19.0, 20.0], [21.0, 22.0], [23.0, 24.0]]
              ]) #(3,4,2)
print("einsum=", np.einsum('ijk,lmj->iklm', a, b))

# Calculate the total number of elements required
# total_elements = np.prod((3, 4, 5,6, 2))

# # Create a 1D array with the required number of elements
# arr = np.arange(start=1,stop=total_elements+1)

# # Reshape the array to the desired shape
# b = arr.reshape((3, 4, 5,6, 2))
#print("einsum=", np.einsum('ij,klmni->jklmn', a, b))



# Perform tensor contraction over specified indices
# Contract A over indices 1 and 2 with B over indices 1 and 0 respectively
# C = np.einsum('ijk,ljm->ilm', A, B)





einsum= [[[[  9.  19.  29.  39.]
   [ 49.  59.  69.  79.]
   [ 89.  99. 109. 119.]]

  [[ 12.  26.  40.  54.]
   [ 68.  82.  96. 110.]
   [124. 138. 152. 166.]]

  [[ 15.  33.  51.  69.]
   [ 87. 105. 123. 141.]
   [159. 177. 195. 213.]]]


 [[[ 27.  61.  95. 129.]
   [163. 197. 231. 265.]
   [299. 333. 367. 401.]]

  [[ 30.  68. 106. 144.]
   [182. 220. 258. 296.]
   [334. 372. 410. 448.]]

  [[ 33.  75. 117. 159.]
   [201. 243. 285. 327.]
   [369. 411. 453. 495.]]]]
