In [ ]:


import numpy as np
import re

def read_formatted_array(file_path):
   # Read the file content
   with open(file_path, 'r') as file:
      file.readline()
      shape = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", file.readline()), dtype=np.uint32)
      strides = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", file.readline()), dtype=np.uint32)
      text = file.read()

   # Extract all numbers using regex
   numbers = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", text), dtype=np.float32)

   # Reshape the array to the desired shape 
   array = numbers.reshape(shape)

   return array


a = np.array([
[
   [
      [  1.0000,  2.0000,  3.0000,  4.0000,  5.0000 ],
      [  6.0000,  7.0000,  8.0000,  9.0000, 10.0000 ],
      [ 11.0000, 12.0000, 13.0000, 14.0000, 15.0000 ],
      [ 16.0000, 17.0000, 18.0000, 19.0000, 20.0000 ]
   ],
   [
      [ 21.0000, 22.0000, 23.0000, 24.0000, 25.0000 ],
      [ 26.0000, 27.0000, 28.0000, 29.0000, 30.0000 ],
      [ 31.0000, 32.0000, 33.0000, 34.0000, 35.0000 ],
      [ 36.0000, 37.0000, 38.0000, 39.0000, 40.0000 ]
   ],
   [
      [ 41.0000, 42.0000, 43.0000, 44.0000, 45.0000 ],
      [ 46.0000, 47.0000, 48.0000, 49.0000, 50.0000 ],
      [ 51.0000, 52.0000, 53.0000, 54.0000, 55.0000 ],
      [ 56.0000, 57.0000, 58.0000, 59.0000, 60.0000 ]
   ]
],
[
   [
      [ 61.0000, 62.0000, 63.0000, 64.0000, 65.0000 ],
      [ 66.0000, 67.0000, 68.0000, 69.0000, 70.0000 ],
      [ 71.0000, 72.0000, 73.0000, 74.0000, 75.0000 ],
      [ 76.0000, 77.0000, 78.0000, 79.0000, 80.0000 ]
   ],
   [
      [ 81.0000, 82.0000, 83.0000, 84.0000, 85.0000 ],
      [ 86.0000, 87.0000, 88.0000, 89.0000, 90.0000 ],
      [ 91.0000, 92.0000, 93.0000, 94.0000, 95.0000 ],
      [ 96.0000, 97.0000, 98.0000, 99.0000,100.0000 ]
   ],
   [
      [101.0000,102.0000,103.0000,104.0000,105.0000 ],
      [106.0000,107.0000,108.0000,109.0000,110.0000 ],
      [111.0000,112.0000,113.0000,114.0000,115.0000 ],
      [116.0000,117.0000,118.0000,119.0000,120.0000 ]
   ]
]
]) # (2,3,4,5)

b =  np.array([
[
   [
      [  1.0000,  2.0000 ],
      [  3.0000,  4.0000 ],
      [  5.0000,  6.0000 ]
   ],
   [
      [  7.0000,  8.0000 ],
      [  9.0000, 10.0000 ],
      [ 11.0000, 12.0000 ]
   ],
   [
      [ 13.0000, 14.0000 ],
      [ 15.0000, 16.0000 ],
      [ 17.0000, 18.0000 ]
   ],
   [
      [ 19.0000, 20.0000 ],
      [ 21.0000, 22.0000 ],
      [ 23.0000, 24.0000 ]
   ]
],
[
   [
      [ 25.0000, 26.0000 ],
      [ 27.0000, 28.0000 ],
      [ 29.0000, 30.0000 ]
   ],
   [
      [ 31.0000, 32.0000 ],
      [ 33.0000, 34.0000 ],
      [ 35.0000, 36.0000 ]
   ],
   [
      [ 37.0000, 38.0000 ],
      [ 39.0000, 40.0000 ],
      [ 41.0000, 42.0000 ]
   ],
   [
      [ 43.0000, 44.0000 ],
      [ 45.0000, 46.0000 ],
      [ 47.0000, 48.0000 ]
   ]
],
[
   [
      [ 49.0000, 50.0000 ],
      [ 51.0000, 52.0000 ],
      [ 53.0000, 54.0000 ]
   ],
   [
      [ 55.0000, 56.0000 ],
      [ 57.0000, 58.0000 ],
      [ 59.0000, 60.0000 ]
   ],
   [
      [ 61.0000, 62.0000 ],
      [ 63.0000, 64.0000 ],
      [ 65.0000, 66.0000 ]
   ],
   [
      [ 67.0000, 68.0000 ],
      [ 69.0000, 70.0000 ],
      [ 71.0000, 72.0000 ]
   ]
],
[
   [
      [ 73.0000, 74.0000 ],
      [ 75.0000, 76.0000 ],
      [ 77.0000, 78.0000 ]
   ],
   [
      [ 79.0000, 80.0000 ],
      [ 81.0000, 82.0000 ],
      [ 83.0000, 84.0000 ]
   ],
   [
      [ 85.0000, 86.0000 ],
      [ 87.0000, 88.0000 ],
      [ 89.0000, 90.0000 ]
   ],
   [
      [ 91.0000, 92.0000 ],
      [ 93.0000, 94.0000 ],
      [ 95.0000, 96.0000 ]
   ]
],
[
   [
      [ 97.0000, 98.0000 ],
      [ 99.0000,100.0000 ],
      [101.0000,102.0000 ]
   ],
   [
      [103.0000,104.0000 ],
      [105.0000,106.0000 ],
      [107.0000,108.0000 ]
   ],
   [
      [109.0000,110.0000 ],
      [111.0000,112.0000 ],
      [113.0000,114.0000 ]
   ],
   [
      [115.0000,116.0000 ],
      [117.0000,118.0000 ],
      [119.0000,120.0000 ]
   ]
]
]) #(5, 4,3,2)

#

c = np.einsum('ijkl,mkni->jlmn', a, b)

# p = np.array([
#   [
#      [  1.0000,  2.0000 ],
#      [  3.0000,  4.0000 ]
#   ],
#   [
#      [  5.0000,  6.0000 ],
#      [  7.0000,  8.0000 ]
#   ]
# ])

# print(np.transpose(p,(2,1,0)))
print("einsum=",np.size(c),c.shape, c)

# Read and convert to NumPy array
d = read_formatted_array("../output.txt")

assert((c == d).all())


In [ ]:


import numpy as np
import re

def read_formatted_array(file_path):
   # Read the file content
   with open(file_path, 'r') as file:
      file.readline()
      shape = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", file.readline()), dtype=np.uint32)
      strides = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", file.readline()), dtype=np.uint32)
      text = file.read()

   # Extract all numbers using regex
   numbers = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", text), dtype=np.float32)

   # Reshape the array to the desired shape 
   array = numbers.reshape(shape)

   return array


a = np.array([
[
   [
      [  1.0000,  2.0000,  3.0000,  4.0000,  5.0000 ],
      [  6.0000,  7.0000,  8.0000,  9.0000, 10.0000 ],
      [ 11.0000, 12.0000, 13.0000, 14.0000, 15.0000 ],
      [ 16.0000, 17.0000, 18.0000, 19.0000, 20.0000 ]
   ],
   [
      [ 21.0000, 22.0000, 23.0000, 24.0000, 25.0000 ],
      [ 26.0000, 27.0000, 28.0000, 29.0000, 30.0000 ],
      [ 31.0000, 32.0000, 33.0000, 34.0000, 35.0000 ],
      [ 36.0000, 37.0000, 38.0000, 39.0000, 40.0000 ]
   ],
   [
      [ 41.0000, 42.0000, 43.0000, 44.0000, 45.0000 ],
      [ 46.0000, 47.0000, 48.0000, 49.0000, 50.0000 ],
      [ 51.0000, 52.0000, 53.0000, 54.0000, 55.0000 ],
      [ 56.0000, 57.0000, 58.0000, 59.0000, 60.0000 ]
   ]
],
[
   [
      [ 61.0000, 62.0000, 63.0000, 64.0000, 65.0000 ],
      [ 66.0000, 67.0000, 68.0000, 69.0000, 70.0000 ],
      [ 71.0000, 72.0000, 73.0000, 74.0000, 75.0000 ],
      [ 76.0000, 77.0000, 78.0000, 79.0000, 80.0000 ]
   ],
   [
      [ 81.0000, 82.0000, 83.0000, 84.0000, 85.0000 ],
      [ 86.0000, 87.0000, 88.0000, 89.0000, 90.0000 ],
      [ 91.0000, 92.0000, 93.0000, 94.0000, 95.0000 ],
      [ 96.0000, 97.0000, 98.0000, 99.0000,100.0000 ]
   ],
   [
      [101.0000,102.0000,103.0000,104.0000,105.0000 ],
      [106.0000,107.0000,108.0000,109.0000,110.0000 ],
      [111.0000,112.0000,113.0000,114.0000,115.0000 ],
      [116.0000,117.0000,118.0000,119.0000,120.0000 ]
   ]
]
]) # (2,3,4,5)

b =  np.array([
[
   [
      [  1.0000,  2.0000 ],
      [  3.0000,  4.0000 ],
      [  5.0000,  6.0000 ]
   ],
   [
      [  7.0000,  8.0000 ],
      [  9.0000, 10.0000 ],
      [ 11.0000, 12.0000 ]
   ],
   [
      [ 13.0000, 14.0000 ],
      [ 15.0000, 16.0000 ],
      [ 17.0000, 18.0000 ]
   ],
   [
      [ 19.0000, 20.0000 ],
      [ 21.0000, 22.0000 ],
      [ 23.0000, 24.0000 ]
   ]
],
[
   [
      [ 25.0000, 26.0000 ],
      [ 27.0000, 28.0000 ],
      [ 29.0000, 30.0000 ]
   ],
   [
      [ 31.0000, 32.0000 ],
      [ 33.0000, 34.0000 ],
      [ 35.0000, 36.0000 ]
   ],
   [
      [ 37.0000, 38.0000 ],
      [ 39.0000, 40.0000 ],
      [ 41.0000, 42.0000 ]
   ],
   [
      [ 43.0000, 44.0000 ],
      [ 45.0000, 46.0000 ],
      [ 47.0000, 48.0000 ]
   ]
],
[
   [
      [ 49.0000, 50.0000 ],
      [ 51.0000, 52.0000 ],
      [ 53.0000, 54.0000 ]
   ],
   [
      [ 55.0000, 56.0000 ],
      [ 57.0000, 58.0000 ],
      [ 59.0000, 60.0000 ]
   ],
   [
      [ 61.0000, 62.0000 ],
      [ 63.0000, 64.0000 ],
      [ 65.0000, 66.0000 ]
   ],
   [
      [ 67.0000, 68.0000 ],
      [ 69.0000, 70.0000 ],
      [ 71.0000, 72.0000 ]
   ]
],
[
   [
      [ 73.0000, 74.0000 ],
      [ 75.0000, 76.0000 ],
      [ 77.0000, 78.0000 ]
   ],
   [
      [ 79.0000, 80.0000 ],
      [ 81.0000, 82.0000 ],
      [ 83.0000, 84.0000 ]
   ],
   [
      [ 85.0000, 86.0000 ],
      [ 87.0000, 88.0000 ],
      [ 89.0000, 90.0000 ]
   ],
   [
      [ 91.0000, 92.0000 ],
      [ 93.0000, 94.0000 ],
      [ 95.0000, 96.0000 ]
   ]
],
[
   [
      [ 97.0000, 98.0000 ],
      [ 99.0000,100.0000 ],
      [101.0000,102.0000 ]
   ],
   [
      [103.0000,104.0000 ],
      [105.0000,106.0000 ],
      [107.0000,108.0000 ]
   ],
   [
      [109.0000,110.0000 ],
      [111.0000,112.0000 ],
      [113.0000,114.0000 ]
   ],
   [
      [115.0000,116.0000 ],
      [117.0000,118.0000 ],
      [119.0000,120.0000 ]
   ]
]
]) #(5, 4,3,2)


c = np.einsum('ijkl,mkni->jlmn', a, b)

print("einsum=",np.size(c),c.shape, c)

# Read and convert to NumPy array
d = read_formatted_array("../output.txt")

assert((c == d).all())


In [33]:
import numpy as np

# https://deus-ex-machina-ism.com/?p=67518&lang=en





def hooi(tensor, rank, max_iter=100, tol=1e-6):
    """
    HOOI (High-Order Orthogonal Iteration) implementation
    :param tensor: Tensors applying the TT decomposition
    :param rank: List of TT ranks.
    :param max_iter: Maximum number of iterations
    :param tol: Tolerance for convergence decision
    :return: TT decomposed tensor sequence
    """
    # Number of dimensions of the tensor
    num_dims = len(rank)
    
    # Initialisation of tensor sequence
    tensor_list = []
    
    # Initialisation of singular vectors for each mode.
    u_matrices = [np.random.rand(tensor.shape[i], rank[i]) for i in range(num_dims)]
    
    # iteration
    for _ in range(max_iter):
        # Singular value decomposition in each mode.
        for i in range(num_dims):
            # Convolution of tensors in mode i.
            mode_products = np.tensordot(tensor, u_matrices[i], axes=(i, 0))
            
            # Singular value decomposition of mode i
            u, _, _ = np.linalg.svd(np.reshape(mode_products, (-1, rank[i])), full_matrices=False)
            u_matrices[i] = u[:, :rank[i]]
        
        # convergence judgment (judgement)
        # For simplicity, convergence is considered here when the change in the singular vector is less than the permissible error
        # The actual convergence decision depends on the problem.
        if np.all([np.linalg.norm(u_matrices[i] - u_matrices[i-1]) < tol for i in range(1, num_dims)]):
            break
    
    # Construction of tensor sequences
    for i in range(num_dims):
        tensor_list.append(u_matrices[i])
    
    return tensor_list

# Tensor example.
tensor = np.random.rand(2, 3, 4)

# Designation of TT ranks
rank = [2, 2, 2]

# Execution of HOOI
tt_tensors = hooi(tensor, rank)

# Display of tensor sequence obtained by HOOI.
for i, tt_tensor in enumerate(tt_tensors):
    print(f"Tensor {i + 1}:")
    print(tt_tensor)
    print()


ValueError: operands could not be broadcast together with shapes (8,2) (12,2) 

In [231]:
import numpy as np
np.set_printoptions(linewidth=200)
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# cal = np.zeros([12*31])
# offset = 0
# for t in range(0,12,1):
#    for d in range(0,31,16):
#       for idx in range(0,4):
#          if (t*31)+d + idx + offset < 12*31:
#             cal[(t*31)+d + idx + offset] = a[idx]
#          if (t*31)+d  + idx + 4 + offset < 12*31:
#             cal[(t*31)+d  + idx + 4 + offset] = b[idx]
#       a = np.roll(a,1)
#       b = np.roll(b,1)     
#    a = np.array([1,2,3,4])
#    b = np.array([5,6,7,8])
#    offset += 4

# print(cal.reshape([12,31]))

cal = np.zeros([12,34])
time_offset = 0
day_offset = 0

for t in range(11,6,-1):
   # if t % 4 == 0:
   #    time_offset = 0
   #    a = np.roll(np.array([1,2,3,4]),1)
   #    b = np.roll(np.array([5,6,7,8]),1)
   
   
   for d in range(0,32,16):
      for idx in range(0,4):
         #if (d + idx + day_offset + time_offset) < 32:
            cal[t,(d + idx + day_offset + time_offset)%34]   = a[idx]
         #if (d + 4 + idx + day_offset + time_offset) < 32:
            cal[t,(d + 4 + idx + day_offset + time_offset)%34] = b[idx]
      #day_offset += 4           
      a = np.roll(a,1)
      b = np.roll(b,1)         
   day_offset = 0
   time_offset += 4  
   a = np.roll(np.array([1,2,3,4]),0)
   b = np.roll(np.array([5,6,7,8]),0)

print(cal[:,:])

   

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 3. 8. 5. 6. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5. 6. 7. 8. 0. 0. 0. 0. 0. 0. 0. 0. 4. 1.]
 [6. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5. 6. 7. 8. 0. 0. 0. 0. 0. 0. 0. 0. 4. 1. 2. 3. 8. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 2. 3. 4. 5. 6. 7. 8. 0. 0.