In [20]:


import numpy as np
import re

import re

def read_formatted_array(file_path):
   # Read the file content
   with open(file_path, 'r') as file:
      file.readline()
      shape = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", file.readline()), dtype=np.uint32)
      strides = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", file.readline()), dtype=np.uint32)
      text = file.read()

   # Extract all numbers using regex
   numbers = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", text), dtype=np.float32)

   # Reshape the array to the desired shape 
   array = numbers.reshape(shape)

   return array


a = np.array([
[
   [
      [  1.0000,  2.0000,  3.0000,  4.0000,  5.0000 ],
      [  6.0000,  7.0000,  8.0000,  9.0000, 10.0000 ],
      [ 11.0000, 12.0000, 13.0000, 14.0000, 15.0000 ],
      [ 16.0000, 17.0000, 18.0000, 19.0000, 20.0000 ]
   ],
   [
      [ 21.0000, 22.0000, 23.0000, 24.0000, 25.0000 ],
      [ 26.0000, 27.0000, 28.0000, 29.0000, 30.0000 ],
      [ 31.0000, 32.0000, 33.0000, 34.0000, 35.0000 ],
      [ 36.0000, 37.0000, 38.0000, 39.0000, 40.0000 ]
   ],
   [
      [ 41.0000, 42.0000, 43.0000, 44.0000, 45.0000 ],
      [ 46.0000, 47.0000, 48.0000, 49.0000, 50.0000 ],
      [ 51.0000, 52.0000, 53.0000, 54.0000, 55.0000 ],
      [ 56.0000, 57.0000, 58.0000, 59.0000, 60.0000 ]
   ]
],
[
   [
      [ 61.0000, 62.0000, 63.0000, 64.0000, 65.0000 ],
      [ 66.0000, 67.0000, 68.0000, 69.0000, 70.0000 ],
      [ 71.0000, 72.0000, 73.0000, 74.0000, 75.0000 ],
      [ 76.0000, 77.0000, 78.0000, 79.0000, 80.0000 ]
   ],
   [
      [ 81.0000, 82.0000, 83.0000, 84.0000, 85.0000 ],
      [ 86.0000, 87.0000, 88.0000, 89.0000, 90.0000 ],
      [ 91.0000, 92.0000, 93.0000, 94.0000, 95.0000 ],
      [ 96.0000, 97.0000, 98.0000, 99.0000,100.0000 ]
   ],
   [
      [101.0000,102.0000,103.0000,104.0000,105.0000 ],
      [106.0000,107.0000,108.0000,109.0000,110.0000 ],
      [111.0000,112.0000,113.0000,114.0000,115.0000 ],
      [116.0000,117.0000,118.0000,119.0000,120.0000 ]
   ]
]
]) # (2,3,4,5)

b =  np.array([
[
   [
      [  1.0000,  2.0000 ],
      [  3.0000,  4.0000 ],
      [  5.0000,  6.0000 ]
   ],
   [
      [  7.0000,  8.0000 ],
      [  9.0000, 10.0000 ],
      [ 11.0000, 12.0000 ]
   ],
   [
      [ 13.0000, 14.0000 ],
      [ 15.0000, 16.0000 ],
      [ 17.0000, 18.0000 ]
   ],
   [
      [ 19.0000, 20.0000 ],
      [ 21.0000, 22.0000 ],
      [ 23.0000, 24.0000 ]
   ]
],
[
   [
      [ 25.0000, 26.0000 ],
      [ 27.0000, 28.0000 ],
      [ 29.0000, 30.0000 ]
   ],
   [
      [ 31.0000, 32.0000 ],
      [ 33.0000, 34.0000 ],
      [ 35.0000, 36.0000 ]
   ],
   [
      [ 37.0000, 38.0000 ],
      [ 39.0000, 40.0000 ],
      [ 41.0000, 42.0000 ]
   ],
   [
      [ 43.0000, 44.0000 ],
      [ 45.0000, 46.0000 ],
      [ 47.0000, 48.0000 ]
   ]
],
[
   [
      [ 49.0000, 50.0000 ],
      [ 51.0000, 52.0000 ],
      [ 53.0000, 54.0000 ]
   ],
   [
      [ 55.0000, 56.0000 ],
      [ 57.0000, 58.0000 ],
      [ 59.0000, 60.0000 ]
   ],
   [
      [ 61.0000, 62.0000 ],
      [ 63.0000, 64.0000 ],
      [ 65.0000, 66.0000 ]
   ],
   [
      [ 67.0000, 68.0000 ],
      [ 69.0000, 70.0000 ],
      [ 71.0000, 72.0000 ]
   ]
],
[
   [
      [ 73.0000, 74.0000 ],
      [ 75.0000, 76.0000 ],
      [ 77.0000, 78.0000 ]
   ],
   [
      [ 79.0000, 80.0000 ],
      [ 81.0000, 82.0000 ],
      [ 83.0000, 84.0000 ]
   ],
   [
      [ 85.0000, 86.0000 ],
      [ 87.0000, 88.0000 ],
      [ 89.0000, 90.0000 ]
   ],
   [
      [ 91.0000, 92.0000 ],
      [ 93.0000, 94.0000 ],
      [ 95.0000, 96.0000 ]
   ]
],
[
   [
      [ 97.0000, 98.0000 ],
      [ 99.0000,100.0000 ],
      [101.0000,102.0000 ]
   ],
   [
      [103.0000,104.0000 ],
      [105.0000,106.0000 ],
      [107.0000,108.0000 ]
   ],
   [
      [109.0000,110.0000 ],
      [111.0000,112.0000 ],
      [113.0000,114.0000 ]
   ],
   [
      [115.0000,116.0000 ],
      [117.0000,118.0000 ],
      [119.0000,120.0000 ]
   ]
]
]) #(5, 4,3,2)

# a= np.array([
#   [
#      [  1.0000,  2.0000 ],
#      [  3.0000,  4.0000 ]
#   ],
#   [
#      [  5.0000,  6.0000 ],
#      [  7.0000,  8.0000 ]
#   ]
# ])

# print(a[0,0,:])
# print(a[0,1,:])
# print(a[1,0,:])
# print(a[1,1,:])

# b= np.array([
#   [
#      [  9.0000, 10.0000 ],
#      [ 11.0000, 12.0000 ]
#   ],
#   [
#      [ 13.0000, 14.0000 ]
#      ,
#      [ 15.0000, 16.0000 ]
#   ]
# ])

# print(b[:,0,0])
# print(b[:,1,0])
# print(b[:,0,1])
# print(b[:,1,1])

c = np.einsum('ijkl,lmno', a, b)
print("einsum=", c)

# Read and convert to NumPy array
d = read_formatted_array("../output.txt")

#assert((c == d).all())


einsum= [[[[[[  975.   990.]
     [ 1005.  1020.]
     [ 1035.  1050.]]

    [[ 1065.  1080.]
     [ 1095.  1110.]
     [ 1125.  1140.]]

    [[ 1155.  1170.]
     [ 1185.  1200.]
     [ 1215.  1230.]]

    [[ 1245.  1260.]
     [ 1275.  1290.]
     [ 1305.  1320.]]]


   [[[ 2200.  2240.]
     [ 2280.  2320.]
     [ 2360.  2400.]]

    [[ 2440.  2480.]
     [ 2520.  2560.]
     [ 2600.  2640.]]

    [[ 2680.  2720.]
     [ 2760.  2800.]
     [ 2840.  2880.]]

    [[ 2920.  2960.]
     [ 3000.  3040.]
     [ 3080.  3120.]]]


   [[[ 3425.  3490.]
     [ 3555.  3620.]
     [ 3685.  3750.]]

    [[ 3815.  3880.]
     [ 3945.  4010.]
     [ 4075.  4140.]]

    [[ 4205.  4270.]
     [ 4335.  4400.]
     [ 4465.  4530.]]

    [[ 4595.  4660.]
     [ 4725.  4790.]
     [ 4855.  4920.]]]


   [[[ 4650.  4740.]
     [ 4830.  4920.]
     [ 5010.  5100.]]

    [[ 5190.  5280.]
     [ 5370.  5460.]
     [ 5550.  5640.]]

    [[ 5730.  5820.]
     [ 5910.  6000.]
     [ 6090.  6180.]]

    [[ 6270