In [34]:


import numpy as np
import re

import re

def read_formatted_array(file_path):
   # Read the file content
   with open(file_path, 'r') as file:
      file.readline()
      shape = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", file.readline()), dtype=np.uint32)
      strides = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", file.readline()), dtype=np.uint32)
      text = file.read()

   # Extract all numbers using regex
   numbers = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", text), dtype=np.float32)

   # Reshape the array to the desired shape 
   array = numbers.reshape(shape)

   return array


a = np.array([
  [
     [
        [  1.0000,  2.0000,  3.0000,  4.0000,  5.0000 ],
        [  6.0000,  7.0000,  8.0000,  9.0000, 10.0000 ],
        [ 11.0000, 12.0000, 13.0000, 14.0000, 15.0000 ],
        [ 16.0000, 17.0000, 18.0000, 19.0000, 20.0000 ]
     ],
     [
        [ 21.0000, 22.0000, 23.0000, 24.0000, 25.0000 ],
        [ 26.0000, 27.0000, 28.0000, 29.0000, 30.0000 ],
        [ 31.0000, 32.0000, 33.0000, 34.0000, 35.0000 ],
        [ 36.0000, 37.0000, 38.0000, 39.0000, 40.0000 ]
     ],
     [
        [ 41.0000, 42.0000, 43.0000, 44.0000, 45.0000 ],
        [ 46.0000, 47.0000, 48.0000, 49.0000, 50.0000 ],
        [ 51.0000, 52.0000, 53.0000, 54.0000, 55.0000 ],
        [ 56.0000, 57.0000, 58.0000, 59.0000, 60.0000 ]
     ]
  ],
  [
     [
        [ 61.0000, 62.0000, 63.0000, 64.0000, 65.0000 ],
        [ 66.0000, 67.0000, 68.0000, 69.0000, 70.0000 ],
        [ 71.0000, 72.0000, 73.0000, 74.0000, 75.0000 ],
        [ 76.0000, 77.0000, 78.0000, 79.0000, 80.0000 ]
     ],
     [
        [ 81.0000, 82.0000, 83.0000, 84.0000, 85.0000 ],
        [ 86.0000, 87.0000, 88.0000, 89.0000, 90.0000 ],
        [ 91.0000, 92.0000, 93.0000, 94.0000, 95.0000 ],
        [ 96.0000, 97.0000, 98.0000, 99.0000,100.0000 ]
     ],
     [
        [101.0000,102.0000,103.0000,104.0000,105.0000 ],
        [106.0000,107.0000,108.0000,109.0000,110.0000 ],
        [111.0000,112.0000,113.0000,114.0000,115.0000 ],
        [116.0000,117.0000,118.0000,119.0000,120.0000 ]
     ]
  ]
]) # (2,3,4,5)

b =  np.array([
  [
     [
        [  1.0000,  2.0000 ],
        [  3.0000,  4.0000 ],
        [  5.0000,  6.0000 ]
     ],
     [
        [  7.0000,  8.0000 ],
        [  9.0000, 10.0000 ],
        [ 11.0000, 12.0000 ]
     ],
     [
        [ 13.0000, 14.0000 ],
        [ 15.0000, 16.0000 ],
        [ 17.0000, 18.0000 ]
     ],
     [
        [ 19.0000, 20.0000 ],
        [ 21.0000, 22.0000 ],
        [ 23.0000, 24.0000 ]
     ]
  ],
  [
     [
        [ 25.0000, 26.0000 ],
        [ 27.0000, 28.0000 ],
        [ 29.0000, 30.0000 ]
     ],
     [
        [ 31.0000, 32.0000 ],
        [ 33.0000, 34.0000 ],
        [ 35.0000, 36.0000 ]
     ],
     [
        [ 37.0000, 38.0000 ],
        [ 39.0000, 40.0000 ],
        [ 41.0000, 42.0000 ]
     ],
     [
        [ 43.0000, 44.0000 ],
        [ 45.0000, 46.0000 ],
        [ 47.0000, 48.0000 ]
     ]
  ],
  [
     [
        [ 49.0000, 50.0000 ],
        [ 51.0000, 52.0000 ],
        [ 53.0000, 54.0000 ]
     ],
     [
        [ 55.0000, 56.0000 ],
        [ 57.0000, 58.0000 ],
        [ 59.0000, 60.0000 ]
     ],
     [
        [ 61.0000, 62.0000 ],
        [ 63.0000, 64.0000 ],
        [ 65.0000, 66.0000 ]
     ],
     [
        [ 67.0000, 68.0000 ],
        [ 69.0000, 70.0000 ],
        [ 71.0000, 72.0000 ]
     ]
  ],
  [
     [
        [ 73.0000, 74.0000 ],
        [ 75.0000, 76.0000 ],
        [ 77.0000, 78.0000 ]
     ],
     [
        [ 79.0000, 80.0000 ],
        [ 81.0000, 82.0000 ],
        [ 83.0000, 84.0000 ]
     ],
     [
        [ 85.0000, 86.0000 ],
        [ 87.0000, 88.0000 ],
        [ 89.0000, 90.0000 ]
     ],
     [
        [ 91.0000, 92.0000 ],
        [ 93.0000, 94.0000 ],
        [ 95.0000, 96.0000 ]
     ]
  ],
  [
     [
        [ 97.0000, 98.0000 ],
        [ 99.0000,100.0000 ],
        [101.0000,102.0000 ]
     ],
     [
        [103.0000,104.0000 ],
        [105.0000,106.0000 ],
        [107.0000,108.0000 ]
     ],
     [
        [109.0000,110.0000 ],
        [111.0000,112.0000 ],
        [113.0000,114.0000 ]
     ],
     [
        [115.0000,116.0000 ],
        [117.0000,118.0000 ],
        [119.0000,120.0000 ]
     ]
  ]
]) #(5, 4,3,2)

c = np.einsum('ijkl,lkno->ijno', a, b)
print("einsum=", c)

# Read and convert to NumPy array
d = read_formatted_array("../output.txt")

#assert((c == d).all())


einsum= [[[[ 13890.  14100.]
   [ 14310.  14520.]
   [ 14730.  14940.]]

  [[ 37090.  37700.]
   [ 38310.  38920.]
   [ 39530.  40140.]]

  [[ 60290.  61300.]
   [ 62310.  63320.]
   [ 64330.  65340.]]]


 [[[ 83490.  84900.]
   [ 86310.  87720.]
   [ 89130.  90540.]]

  [[106690. 108500.]
   [110310. 112120.]
   [113930. 115740.]]

  [[129890. 132100.]
   [134310. 136520.]
   [138730. 140940.]]]]
