In [33]:


import numpy as np
import re

import re

def read_formatted_array(file_path):
   # Read the file content
   with open(file_path, 'r') as file:
      file.readline()
      shape = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", file.readline()), dtype=np.uint32)
      strides = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", file.readline()), dtype=np.uint32)
      text = file.read()

   # Extract all numbers using regex
   numbers = np.array(re.findall(r"[-+]?\d*\.\d+|\d+", text), dtype=np.float32)

   # Reshape the array to the desired shape 
   array = numbers.reshape(shape)

   return array


a = np.array([
[
   [
      [  1.0000,  2.0000,  3.0000,  4.0000,  5.0000 ],
      [  6.0000,  7.0000,  8.0000,  9.0000, 10.0000 ],
      [ 11.0000, 12.0000, 13.0000, 14.0000, 15.0000 ],
      [ 16.0000, 17.0000, 18.0000, 19.0000, 20.0000 ]
   ],
   [
      [ 21.0000, 22.0000, 23.0000, 24.0000, 25.0000 ],
      [ 26.0000, 27.0000, 28.0000, 29.0000, 30.0000 ],
      [ 31.0000, 32.0000, 33.0000, 34.0000, 35.0000 ],
      [ 36.0000, 37.0000, 38.0000, 39.0000, 40.0000 ]
   ],
   [
      [ 41.0000, 42.0000, 43.0000, 44.0000, 45.0000 ],
      [ 46.0000, 47.0000, 48.0000, 49.0000, 50.0000 ],
      [ 51.0000, 52.0000, 53.0000, 54.0000, 55.0000 ],
      [ 56.0000, 57.0000, 58.0000, 59.0000, 60.0000 ]
   ]
],
[
   [
      [ 61.0000, 62.0000, 63.0000, 64.0000, 65.0000 ],
      [ 66.0000, 67.0000, 68.0000, 69.0000, 70.0000 ],
      [ 71.0000, 72.0000, 73.0000, 74.0000, 75.0000 ],
      [ 76.0000, 77.0000, 78.0000, 79.0000, 80.0000 ]
   ],
   [
      [ 81.0000, 82.0000, 83.0000, 84.0000, 85.0000 ],
      [ 86.0000, 87.0000, 88.0000, 89.0000, 90.0000 ],
      [ 91.0000, 92.0000, 93.0000, 94.0000, 95.0000 ],
      [ 96.0000, 97.0000, 98.0000, 99.0000,100.0000 ]
   ],
   [
      [101.0000,102.0000,103.0000,104.0000,105.0000 ],
      [106.0000,107.0000,108.0000,109.0000,110.0000 ],
      [111.0000,112.0000,113.0000,114.0000,115.0000 ],
      [116.0000,117.0000,118.0000,119.0000,120.0000 ]
   ]
]
]) # (2,3,4,5)

b =  np.array([
[
   [
      [  1.0000,  2.0000 ],
      [  3.0000,  4.0000 ],
      [  5.0000,  6.0000 ]
   ],
   [
      [  7.0000,  8.0000 ],
      [  9.0000, 10.0000 ],
      [ 11.0000, 12.0000 ]
   ],
   [
      [ 13.0000, 14.0000 ],
      [ 15.0000, 16.0000 ],
      [ 17.0000, 18.0000 ]
   ],
   [
      [ 19.0000, 20.0000 ],
      [ 21.0000, 22.0000 ],
      [ 23.0000, 24.0000 ]
   ]
],
[
   [
      [ 25.0000, 26.0000 ],
      [ 27.0000, 28.0000 ],
      [ 29.0000, 30.0000 ]
   ],
   [
      [ 31.0000, 32.0000 ],
      [ 33.0000, 34.0000 ],
      [ 35.0000, 36.0000 ]
   ],
   [
      [ 37.0000, 38.0000 ],
      [ 39.0000, 40.0000 ],
      [ 41.0000, 42.0000 ]
   ],
   [
      [ 43.0000, 44.0000 ],
      [ 45.0000, 46.0000 ],
      [ 47.0000, 48.0000 ]
   ]
],
[
   [
      [ 49.0000, 50.0000 ],
      [ 51.0000, 52.0000 ],
      [ 53.0000, 54.0000 ]
   ],
   [
      [ 55.0000, 56.0000 ],
      [ 57.0000, 58.0000 ],
      [ 59.0000, 60.0000 ]
   ],
   [
      [ 61.0000, 62.0000 ],
      [ 63.0000, 64.0000 ],
      [ 65.0000, 66.0000 ]
   ],
   [
      [ 67.0000, 68.0000 ],
      [ 69.0000, 70.0000 ],
      [ 71.0000, 72.0000 ]
   ]
],
[
   [
      [ 73.0000, 74.0000 ],
      [ 75.0000, 76.0000 ],
      [ 77.0000, 78.0000 ]
   ],
   [
      [ 79.0000, 80.0000 ],
      [ 81.0000, 82.0000 ],
      [ 83.0000, 84.0000 ]
   ],
   [
      [ 85.0000, 86.0000 ],
      [ 87.0000, 88.0000 ],
      [ 89.0000, 90.0000 ]
   ],
   [
      [ 91.0000, 92.0000 ],
      [ 93.0000, 94.0000 ],
      [ 95.0000, 96.0000 ]
   ]
],
[
   [
      [ 97.0000, 98.0000 ],
      [ 99.0000,100.0000 ],
      [101.0000,102.0000 ]
   ],
   [
      [103.0000,104.0000 ],
      [105.0000,106.0000 ],
      [107.0000,108.0000 ]
   ],
   [
      [109.0000,110.0000 ],
      [111.0000,112.0000 ],
      [113.0000,114.0000 ]
   ],
   [
      [115.0000,116.0000 ],
      [117.0000,118.0000 ],
      [119.0000,120.0000 ]
   ]
]
]) #(5, 4,3,2)

# a= np.array([
#   [
#      [  1.0000,  2.0000 ],
#      [  3.0000,  4.0000 ]
#   ],
#   [
#      [  5.0000,  6.0000 ],
#      [  7.0000,  8.0000 ]
#   ]
# ])

# print(a[0,0,:])
# print(a[0,1,:])
# print(a[1,0,:])
# print(a[1,1,:])

# b= np.array([
#   [
#      [  9.0000, 10.0000 ],
#      [ 11.0000, 12.0000 ]
#   ],
#   [
#      [ 13.0000, 14.0000 ]
#      ,
#      [ 15.0000, 16.0000 ]
#   ]
# ])

# print(b[:,0,0])
# print(b[:,1,0])
# print(b[:,0,1])
# print(b[:,1,1])

# a=np.array([
#   [
#      [  1.0000,  2.0000,  3.0000,  4.0000 ],
#      [  5.0000,  6.0000,  7.0000,  8.0000 ],
#      [  9.0000, 10.0000, 11.0000, 12.0000 ]
#   ],
#   [
#      [ 13.0000, 14.0000, 15.0000, 16.0000 ],
#      [ 17.0000, 18.0000, 19.0000, 20.0000 ],
#      [ 21.0000, 22.0000, 23.0000, 24.0000 ]
#   ]
# ])

# b=np.array([
#   [
#      [ 25.0000, 26.0000, 27.0000, 28.0000, 29.0000, 30.0000 ],
#      [ 31.0000, 32.0000, 33.0000, 34.0000, 35.0000, 36.0000 ],
#      [ 37.0000, 38.0000, 39.0000, 40.0000, 41.0000, 42.0000 ],
#      [ 43.0000, 44.0000, 45.0000, 46.0000, 47.0000, 48.0000 ],
#      [ 49.0000, 50.0000, 51.0000, 52.0000, 53.0000, 54.0000 ]
#   ],
#   [
#      [ 55.0000, 56.0000, 57.0000, 58.0000, 59.0000, 60.0000 ],
#      [ 61.0000, 62.0000, 63.0000, 64.0000, 65.0000, 66.0000 ],
#      [ 67.0000, 68.0000, 69.0000, 70.0000, 71.0000, 72.0000 ],
#      [ 73.0000, 74.0000, 75.0000, 76.0000, 77.0000, 78.0000 ],
#      [ 79.0000, 80.0000, 81.0000, 82.0000, 83.0000, 84.0000 ]
#   ],
#   [
#      [ 85.0000, 86.0000, 87.0000, 88.0000, 89.0000, 90.0000 ],
#      [ 91.0000, 92.0000, 93.0000, 94.0000, 95.0000, 96.0000 ],
#      [ 97.0000, 98.0000, 99.0000,100.0000,101.0000,102.0000 ],
#      [103.0000,104.0000,105.0000,106.0000,107.0000,108.0000 ],
#      [109.0000,110.0000,111.0000,112.0000,113.0000,114.0000 ]
#   ],
#   [
#      [115.0000,116.0000,117.0000,118.0000,119.0000,120.0000 ],
#      [121.0000,122.0000,123.0000,124.0000,125.0000,126.0000 ],
#      [127.0000,128.0000,129.0000,130.0000,131.0000,132.0000 ],
#      [133.0000,134.0000,135.0000,136.0000,137.0000,138.0000 ],
#      [139.0000,140.0000,141.0000,142.0000,143.0000,144.0000 ]
#   ]
# ])

# lh = np.array([])
# for i in range(a.shape[0]):
#    for j in range(a.shape[2]):
#       for k in range(a.shape[1]):
#          #print("a[{i},{j}, {k}]=", a[i,j,k])
#          lh = np.append(lh, a[i,k,j])
         
# print("lh=",lh)
         
# rh = np.array([])         
# for i in range(b.shape[2]):
#    for j in range(b.shape[1]):
#       for k in range(b.shape[0]):
#          rh = np.append(rh, b[k,j,i])
         
# print("rh=",np.size(rh), rh)

# # print("a slice 0,0,:" , a[0,0,:])
# # print("b slice :,0,0" ,b[:,0,0])
# # print("a slice 0,0,:" , a[0,0,:])
# # print("b slice :,0,1" ,b[:,0,1])

# print("c :,:,0 = ", np.dot(a[0,0,:],b[:,0,0]))
# print("c :,:,0 = ", np.dot(a[0,0,:],b[:,0,0]))

c = np.einsum('ijkl,mnjo', a, b)
print("einsum=",np.size(c),c.shape, c)

# Read and convert to NumPy array
d = read_formatted_array("../output.txt")

assert((c == d).all())


einsum= 1600 (2, 4, 5, 5, 4, 2) [[[[[[  269.   332.]
     [  647.   710.]
     [ 1025.  1088.]
     [ 1403.  1466.]]

    [[ 1781.  1844.]
     [ 2159.  2222.]
     [ 2537.  2600.]
     [ 2915.  2978.]]

    [[ 3293.  3356.]
     [ 3671.  3734.]
     [ 4049.  4112.]
     [ 4427.  4490.]]

    [[ 4805.  4868.]
     [ 5183.  5246.]
     [ 5561.  5624.]
     [ 5939.  6002.]]

    [[ 6317.  6380.]
     [ 6695.  6758.]
     [ 7073.  7136.]
     [ 7451.  7514.]]]


   [[[  278.   344.]
     [  674.   740.]
     [ 1070.  1136.]
     [ 1466.  1532.]]

    [[ 1862.  1928.]
     [ 2258.  2324.]
     [ 2654.  2720.]
     [ 3050.  3116.]]

    [[ 3446.  3512.]
     [ 3842.  3908.]
     [ 4238.  4304.]
     [ 4634.  4700.]]

    [[ 5030.  5096.]
     [ 5426.  5492.]
     [ 5822.  5888.]
     [ 6218.  6284.]]

    [[ 6614.  6680.]
     [ 7010.  7076.]
     [ 7406.  7472.]
     [ 7802.  7868.]]]


   [[[  287.   356.]
     [  701.   770.]
     [ 1115.  1184.]
     [ 1529.  1598.]]

    [[ 1943.  2012